publicURL:
connectors:
  - type: mockCallback
    id: mock
    name: Example
secret:
  key:
  store:
    name: default
    kind: ClusterSecretStore

operator:
  image: ghcr.io/karavel-io/dex-operator
  tag: main

dex:
  image: ghcr.io/dexidp/dex
  tag:
prometheus:
  enable: false
