{{- if .Values.prometheus.enable }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "dex.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "dex.name" . }}
    {{- include "dex.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: dex.karavel.io/v1alpha1
    kind: Dex
    name: {{ include "dex.name" . }}
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 80
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 70
{{- end }}
