{{- if .Values.secret }}
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ include "dex.name" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dex.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ .Values.secret.store.name }}
    kind: {{ .Values.secret.store.kind }}
  target:
    creationPolicy: 'Owner'
  dataFrom:
    - key: {{ required (printf "parameter 'secret.key' is required for generating %s-secrets" (include "dex.name" .)) .Values.secret.key }}


