apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dex.name" . }}-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "dex.name" . }}-operator
  {{- include "dex.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "dex.name" . }}-operator
  {{- include "dex.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "dex.name" . }}-operator
    {{- include "dex.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "dex.name" . }}-operator
      containers:
        - name: manager
          image: "{{ .Values.operator.image }}:{{ .Values.operator.tag }}"
          command:
            - /manager
          args:
          - --health-probe-bind-address=:8081
          - --metrics-bind-address=127.0.0.1:8080
          - --leader-elect
          - --dex-default-image
          - {{ .Values.dex.image }}:{{ .Values.dex.tag | default (printf "v%s" .Chart.AppVersion) }}
          imagePullPolicy: {{ ternary "Always" "IfNotPresent" (eq .Values.operator.tag "latest") }}
          ports:
            - name: webhook-server
              containerPort: 9443
              protocol: TCP
            - name: metrics
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
            requests:
              cpu: 100m
              memory: 20Mi
      terminationGracePeriodSeconds: 10
      restartPolicy: Always
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: {{ include "dex.name" . }}-operator-cert
